GET http://127.0.0.1:3000/range?min=1&max=100&number=50

###
GET http://127.0.0.1:3000/range/1/100/50

###
GET http://127.0.0.1:3000/test

### joke service
GET http://127.0.0.1:3000/joke

### 8-ball service
POST  http://127.0.0.1:3000/predict
Content-Type: application/json

{
  "question": "Will this work?"
}

### jsfuck service
POST  http://127.0.0.1:3000/
Content-Type: application/json

{
  "text": "console.log(\"wow\")"
}